---
name: Run unittests
permissions:
  contents: read

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  format:
    name: Ensure tests are passing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - run: pip install pytest

      - run: pip install --editable .

      - name: Run tests
        run: pytest
